version: '3.8'
services:
  db:
    container_name: labo4
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=cestpolo
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=labo4
    ports:
      - '5777:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
